#!/usr/bin/env python3
"""
Rebuild docs/agent-logs/_index.md from every *.jsonl beneath docs/agent-logs/.

Each row: date · author folder · session id · first user prompt (truncated).

Run locally:
    python scripts/build-log-index.py

Run in CI via .github/workflows/build-log-index.yml after a JSONL lands on main.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parent.parent
LOGS_ROOT = REPO_ROOT / "docs" / "agent-logs"
INDEX_PATH = LOGS_ROOT / "_index.md"

PREVIEW_MAX = 100  # chars from first user prompt to show as summary


def first_user_prompt(jsonl_path: Path) -> Optional[str]:
    """Return the first user message text inside a Claude Code session JSONL, or None."""
    try:
        with jsonl_path.open("r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    continue
                # Claude Code session entries have varying shapes; pick the
                # earliest entry that looks like a user message with text.
                role = obj.get("role") or obj.get("type")
                if role in ("user", "human"):
                    content = obj.get("content") or obj.get("text") or ""
                    if isinstance(content, list):
                        # Anthropic-style content blocks
                        for block in content:
                            if isinstance(block, dict) and block.get("type") == "text":
                                return _truncate(block.get("text", ""))
                    elif isinstance(content, str) and content:
                        return _truncate(content)
    except OSError:
        return None
    return None


def _truncate(s: str) -> str:
    s = s.replace("\n", " ").strip()
    if len(s) <= PREVIEW_MAX:
        return s
    return s[: PREVIEW_MAX - 1].rstrip() + "…"


def parse_filename(p: Path) -> tuple[str, str]:
    """File name pattern: YYYY-MM-DD_<sessionId>.jsonl  →  (date, sessionId).
    Falls back gracefully if the pattern doesn't match.
    """
    stem = p.stem
    if "_" in stem:
        date, _, sid = stem.partition("_")
        return date, sid
    return "----", stem


def main() -> int:
    if not LOGS_ROOT.exists():
        print(f"No {LOGS_ROOT} folder — nothing to index.")
        return 0

    rows: list[tuple[str, str, str, str, str]] = []  # (date, handle, session, preview, rel_path)
    for jsonl in sorted(LOGS_ROOT.glob("**/*.jsonl")):
        rel = jsonl.relative_to(REPO_ROOT)
        handle = jsonl.parent.name
        date, sid = parse_filename(jsonl)
        preview = first_user_prompt(jsonl) or ""
        rows.append((date, handle, sid, preview, rel.as_posix()))

    # Newest first
    rows.sort(reverse=True)

    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/build-log-index.py — do not edit by hand. -->",
        "# DroneAid — Agent log index",
        "",
        f"Total sessions: **{len(rows)}**",
        "",
        "| Date | Author | Session | Summary | File |",
        "|---|---|---|---|---|",
    ]
    for date, handle, sid, preview, rel in rows:
        sid_short = (sid[:8] + "…") if len(sid) > 9 else sid
        preview_md = preview.replace("|", "\\|")
        lines.append(f"| {date} | {handle} | `{sid_short}` | {preview_md} | [`{rel}`](../../{rel}) |")

    INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {INDEX_PATH} with {len(rows)} entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
